(function initDomCache() {
    const dom = {
        setupScreen: document.getElementById('setup-screen'),
        meetingScreen: document.getElementById('meeting-screen'),
        summaryScreen: document.getElementById('summary-screen'),
        timeline: document.getElementById('timeline'),
        liveFocusText: document.getElementById('live-focus-text'),
        liveFocusSpeaker: document.getElementById('live-focus-speaker'),
        liveFocusStatus: document.getElementById('live-focus-status'),
        liveFocusTime: document.getElementById('live-focus-time'),
        liveFocusLevel: document.getElementById('live-focus-level'),
        btnJumpLatestFloating: document.getElementById('btn-jump-latest-floating'),
        mobileLogScrollbar: document.getElementById('mobile-log-scrollbar'),
        mobileLogScrollThumb: document.getElementById('mobile-log-scroll-thumb'),
        meetingTitleInput: document.getElementById('meeting-title-input'),
        meetingTitleReadonly: document.getElementById('meeting-title-readonly'),
        mobileMeetingTitleInput: document.getElementById('mobile-meeting-title-input'),
        summaryLog: document.getElementById('summary-log'),
        roomInfo: document.getElementById('room-info'),
        summaryInfo: document.getElementById('summary-info'),
        selfInfo: document.getElementById('self-info'),
        aiWorkspaceStatus: document.getElementById('ai-workspace-status'),
        minutesWorkspaceStatus: document.getElementById('minutes-workspace-status'),
        aiOutputTitle: document.getElementById('ai-output-title'),
        aiOutputCard: document.getElementById('ai-output-card'),
        aiOutputLoading: document.getElementById('ai-output-loading'),
        customAiInstruction: document.getElementById('custom-ai-instruction'),
        aiOutputEditor: document.getElementById('ai-output-editor'),
        minutesOutputCard: document.getElementById('minutes-output-card'),
        minutesOutputLoading: document.getElementById('minutes-output-loading'),
        minutesOutputEditor: document.getElementById('minutes-output-editor'),
        meetingAiStatus: document.getElementById('meeting-ai-status'),
        micCheckStatus: document.getElementById('mic-check-status'),
        micLevelBar: document.getElementById('mic-level-bar'),
        micPresetSummary: document.getElementById('mic-preset-summary'),
        meetingMicPresetSummary: document.getElementById('meeting-mic-preset-summary'),
        setupMicReverberant: document.getElementById('mic-reverberant'),
        meetingMicReverberant: document.getElementById('meeting-mic-reverberant'),
        micMeterShell: document.getElementById('mic-meter-shell'),
        mobileMeetingMenu: document.getElementById('mobile-meeting-menu'),
        summaryMobileMenu: document.getElementById('summary-mobile-menu'),
        editModalOverlay: document.getElementById('edit-modal-overlay'),
        editModalSpeaker: document.getElementById('edit-modal-speaker'),
        editModalTime: document.getElementById('edit-modal-time'),
        editModalOriginal: document.getElementById('edit-modal-original'),
        editModalTextarea: document.getElementById('edit-modal-textarea'),
        memoModalOverlay: document.getElementById('memo-modal-overlay'),
        memoModalSpeaker: document.getElementById('memo-modal-speaker'),
        memoModalTime: document.getElementById('memo-modal-time'),
        memoModalOriginal: document.getElementById('memo-modal-original'),
        memoModalTextarea: document.getElementById('memo-modal-textarea'),
        aiProvider: document.getElementById('ai-provider'),
        dictTerm: document.getElementById('dict-term'),
        dictReading: document.getElementById('dict-reading'),
        dictBulkText: document.getElementById('dict-bulk-text'),
        btnDictAdd: document.getElementById('btn-dict-add'),
        btnDictExtract: document.getElementById('btn-dict-extract'),
        btnDictAddSelected: document.getElementById('btn-dict-add-selected'),
        extractResultsArea: document.getElementById('dict-extract-results'),
        extractList: document.getElementById('extract-list'),
        dictionaryList: document.getElementById('dictionary-list'),
        meetingAiEditors: {
            summary: document.getElementById('meeting-ai-summary'),
            todo: document.getElementById('meeting-ai-todo'),
            agreements: document.getElementById('meeting-ai-agreements'),
            topics: document.getElementById('meeting-ai-topics')
        },
        meetingAiButtons: {
            summary: document.getElementById('btn-meeting-summary'),
            todo: document.getElementById('btn-meeting-todo'),
            agreements: document.getElementById('btn-meeting-agreements'),
            topics: document.getElementById('btn-meeting-topics')
        },
        filterInputs: [
            document.getElementById('log-search'),
            document.getElementById('summary-search')
        ],
        filterButtons: {
            starred: [document.getElementById('filter-starred'), document.getElementById('summary-filter-starred')],
            mine: [document.getElementById('filter-mine'), document.getElementById('summary-filter-mine')],
            noted: [document.getElementById('filter-noted'), document.getElementById('summary-filter-noted')]
        }
    };

    window.AppDom = dom;
})();
